pipelines:
  branches:
    staging:
      - step:
          image: node:18.16
          caches:
            - node
          script:
            - npm install
            - unset CI
            - export MY_PLAYCONOMICS_BASE_URL=https://my.stg.playconomics.com/
            - npm run build
            - export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
            - export S3_BUCKET_NAME=stg.lionsheartstudios.com
            - npm run deploy
    live:
      - step:
          image: node:18.16
          caches:
            - node
          script:
            - npm install
            - unset CI
            - export MY_PLAYCONOMICS_BASE_URL=https://my.playconomics.com/
            - npm run build
            - export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
            - export S3_BUCKET_NAME=lionsheartstudios.com
            - npm run deploy
