pipelines:
  branches:
    staging:
      - step:
          image: node:18.16
          caches:
            - node
            - docker
          script:
            # Install AWS CLI
            # - apt-get update && apt-get install -y git-core python3 python3-pip python3-dev python3-setuptools --no-install-recommends
            # - pip3 --no-cache-dir install --upgrade awscli pyyaml
            # Install deps and compile frontend
            - npm install
            - unset CI
            - npm run build
            - export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
            - export S3_BUCKET_NAME=lionsheartstudios-website
            - npm run deploy
