backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: static/img
public_folder: /img

collections:
  - label: "Sections"
    name: "sections"
    files:
      - label: "About"
        name: "about"
        file: "content/about.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "MainColour", name: "mainColour", widget: "color" }
          - { label: "SecondaryColour", name: "secondaryColour", widget: "color" }
          - { label: "TextColour", name: "textColour", widget: "color" }
          - label: "Intro"
            name: "intro"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Body", name: "body", widget: "text" }