backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - label: "Sections"
    name: "sections"
    files:
      - label: "About"
        name: "about"
        file: "content/about.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - label: "Palette"
            name: "palette"
            widget: "object"
            fields:
              - { label: "Main", name: "main", widget: "color" }
              - { label: "Secondary", name: "secondary", widget: "color" }
              - { label: "Text", name: "text", widget: "color" }
          - label: "Translate"
            name: "translate"
            widget: "object"
            fields:
              - { label: "StartX", name: "startx", widget: "string" }
              - { label: "EndX", name: "endx", widget: "string" }
              - { label: "StartY", name: "starty", widget: "string" }
              - { label: "EndY", name: "endy", widget: "string" }
          - { label: "Wave", name: "wave", widget: "string" }
          - label: "Intro"
            name: "intro"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Body", name: "body", widget: "markdown" }
          - { label: "FullsizeVideo", name: "fullsizevideo", widget: "string" }
          - label: "Partners"
            name: "partners"
            widget: "list"
            fields:
              - { label: "Partner", name: "partner", widget: "string" }
      - label: "Features"
        name: "features"
        file: "content/features.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - label: "Palette"
            name: "palette"
            widget: "object"
            fields:
              - { label: "Main", name: "main", widget: "color" }
              - { label: "Secondary", name: "secondary", widget: "color" }
              - { label: "Text", name: "text", widget: "color" }
          - label: "Translate"
            name: "translate"
            widget: "object"
            fields:
              - { label: "StartX", name: "startx", widget: "string" }
              - { label: "EndX", name: "endx", widget: "string" }
              - { label: "StartY", name: "starty", widget: "string" }
              - { label: "EndY", name: "endy", widget: "string" }
          - { label: "Wave", name: "wave", widget: "string" }
          - label: "Awards"
            name: "awards"
            widget: "list"
            fields:
              - { label: "Award", name: "award", widget: "string" }
              - { label: "Year", name: "year", widget: "string" }
          - { label: "FullsizeVideo", name: "fullsizevideo", widget: "string" }
          - label: "Details"
            name: "details"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Body", name: "body", widget: "markdown" }
      - label: "Contact"
        name: "contact"
        file: "content/contact.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - label: "Palette"
            name: "palette"
            widget: "object"
            fields:
              - { label: "Main", name: "main", widget: "color" }
              - { label: "Secondary", name: "secondary", widget: "color" }
              - { label: "Text", name: "text", widget: "color" }
          - label: "Translate"
            name: "translate"
            widget: "object"
            fields:
              - { label: "StartX", name: "startx", widget: "string" }
              - { label: "EndX", name: "endx", widget: "string" }
              - { label: "StartY", name: "starty", widget: "string" }
              - { label: "EndY", name: "endy", widget: "string" }
          - { label: "Wave", name: "wave", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
