backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - label: "Sections"
    name: "sections"
    files:
      - label: "About"
        name: "about"
        file: "content/about.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - label: "Palette"
            name: "palette"
            widget: "list"
            fields:
              - { label: "Main", name: "main", widget: "color" }
              - { label: "Secondary", name: "secondary", widget: "color" }
              - { label: "Text", name: "text", widget: "color" }
          - label: "Intro"
            name: "intro"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Body", name: "body", widget: "text" }
          - { label: "FullsizeVideo", name: "fullsizevideo", widget: "string" }
          - label: "Partners"
            name: "partners"
            widget: "list"
            fields:
              - { label: "Partner", name: "partner", widget: "string" }