backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - label: "Sections"
    name: "sections"
    folder: "content"
    files:
      - label: "About"
        name: "about"
        file: "content/about.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Main", name: "main", widget: "color" }
          - { label: "Secondary", name: "secondary", widget: "color" }
          - { label: "Text", name: "text", widget: "color" }
          - label: "TranslateX"
            name: "translatex"
            widget: "list"
            field:
              - { label: "Start", name: "start", widget: "number" }
              - { label: "End", name: "end", widget: "number" }
          - label: "Intro"
            name: "intro"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Body", name: "body", widget: "markdown" }
          - { label: "FullsizeVideo", name: "fullsizevideo", widget: "string" }
          - label: "Partners"
            name: "partners"
            widget: "list"
            fields:
              - { label: "Partner", name: "partner", widget: "string" }
      - label: "Features"
        name: "features"
        file: "content/features.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Main", name: "main", widget: "color" }
          - { label: "Secondary", name: "secondary", widget: "color" }
          - { label: "Text", name: "text", widget: "color" }
          - label: "Awards"
            name: "awards"
            widget: "list"
            fields:
              - { label: "Award", name: "award", widget: "string" }
              - { label: "Year", name: "year", widget: "string" }
          - { label: "FullsizeVideo", name: "fullsizevideo", widget: "string" }
          - label: "Details"
            name: "details"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Body", name: "body", widget: "markdown" }
      - label: "Contact"
        name: "contact"
        file: "content/contact.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Main", name: "main", widget: "color" }
          - { label: "Secondary", name: "secondary", widget: "color" }
          - { label: "Text", name: "text", widget: "color" }
          - { label: "Body", name: "body", widget: "markdown" }